### ISSUE TITLE
panic: open ./feditext.config: no such file or directory

### ISSUE THREAD

**Issue by GarfieldsPipe** [KushBlazingJudah/feditext#1]
./feditext
panic: open ./feditext.config: no such file or directory

goroutine 1 [running]:
main.main()
	./home/feditext/cmd/feditext/main.go:10 +0x7a

**Comment by KushBlazingJudah** [comment]
copy `doc/config.example` to `./feditext.config`, read the contents and it should just work.
i apologize for not writing instructions on this, i thought i did.
