### ISSUE TITLE
Blank page after replying

### ISSUE THREAD

**Issue by GarfieldsPipe** [KushBlazingJudah/feditext#5]
When I reply to a thread, I get shown a completely blank page. The post goes through and displays, but first I have to manually go back to see it.

There's no errors in the browser or browser console and the server terminal just shows `2022/06/05 18:08:33 16ms REDACTEDIP POST 302 /b/1`

**Comment by KushBlazingJudah** [comment]
A lot of work has been done on the post forms in the `dev` branch. Can you reproduce the issue there?

**Comment by GarfieldsPipe** [comment]
> A lot of work has been done on the post forms in the `dev` branch. Can you reproduce the issue there?

👌🏻
