### ISSUE TITLE
Make post filters case-insensitive

### ISSUE THREAD

**Issue by GarfieldsPipe** [KushBlazingJudah/feditext#7]
Post filters are currently easily circumventable by changing the letter case.

**Comment by KushBlazingJudah** [comment]
Filters are passed directly to Go's regexp module, which accepts a couple of options which can go at the start of your regexp. Specifically, `(?i)` at the start of any regexp will make the regexp case insensitive.
`(?i)example` will match both `ExAmPlE` and `example`.

For a full reference of what you can do with filters, see <https://pkg.go.dev/regexp/syntax>.
Will clarify eventually on the admin page, next time I get around to working on this.

**Comment by GarfieldsPipe** [comment]
> Filters are passed directly to Go's regexp module, which accepts a couple of options which can go at the start of your regexp. Specifically, `(?i)` at the start of any regexp will make the regexp case insensitive. `(?i)example` will match both `ExAmPlE` and `example`.
> 
> For a full reference of what you can do with filters, see https://pkg.go.dev/regexp/syntax. Will clarify eventually on the admin page, next time I get around to working on this.

Sweet, thanks.
